spring:
  cloud:
    nacos:
      server-addr: ${nacos.host:docker-server}:${nacos.port:8848}
      discovery:
        group: ${nacos.group:gemini}
        namespace: ${nacos.namespace:5e632956-936e-4df8-a4e1-aad059fe7831}
      config:
        group: ${nacos.group:gemini}
        namespace: ${nacos.namespace:5e632956-936e-4df8-a4e1-aad059fe7831}
  config:
    import:
      - optional:nacos:application-${spring.profiles.active:dev}.yml
      - optional:nacos:${spring.application.name}-${spring.profiles.active:dev}.yml