spring:
  cloud:
    nacos:
      server-addr: ${nacos.host:docker-server}:${nacos.port:8848}
      discovery:
        group: ${nacos.group:gemini}
        namespace: ${nacos.namespace:cc7d8bb5-1db6-4766-9dff-fd9dd012328c}
      config:
        group: ${nacos.group:gemini}
        namespace: ${nacos.namespace:cc7d8bb5-1db6-4766-9dff-fd9dd012328c}
  config:
    import:
      - optional:nacos:application-${spring.profiles.active:dev}.yml?refresh=true
      - optional:nacos:${spring.application.name}-${spring.profiles.active:dev}.yml?refresh=true